ard:
  fqbn: "--fqbn=arduino:avr:uno --fqbn=Infineon:xmc:KIT_XMC_2GO_XMC1100_V1 --fqbn=Infineon:xmc:KIT_XMC11_BOOT_001 --fqbn=Infineon:xmc:KIT_XMC13_BOOT_001 --fqbn=Infineon:xmc:KIT_XMC14_2GO --fqbn=Infineon:xmc:KIT_XMC1400_ARDUINO --fqbn=Infineon:xmc:XMC4200_Platform2GO --fqbn=Infineon:xmc:XMC4400_Platform2GO --fqbn=Infineon:xmc:KIT_XMC47_RELAX"

pio:
  boards: "--board=uno --board=kit_xmc_2go_xmc1100_v1 --board=xmc1100_boot_kit --board=kit_xmc47_relax"
  options: "--project-option=\"lib_deps=Wire\""

hil:
  fqbn:         Infineon:xmc:KIT_XMC_2GO_XMC1100_V1
  example:      "examples/readAngleTest"
  baud:         9600
  timeout:      10
  version:      4.0.1

